export const en = {
  meta: {
    homeTitle: 'Optimix — Business process optimization',
    homeDescription: 'Optimix helps operations teams redesign repeated handoffs into controlled workflows, with people responsible for approvals and exceptions.',
    contactTitle: 'Prepare a process brief — Optimix',
    contactDescription: 'Describe one repeated business process, the people and systems involved, and where work slows down.',
    privacyTitle: 'Privacy information — Optimix',
    privacyDescription: 'Information about the current status of the Optimix inquiry form and privacy notice.',
  },
  ui: {
    skip: 'Skip to content',
    process: 'Process',
    approach: 'Approach',
    contact: 'Contact',
    brief: 'Prepare a process brief',
    briefShort: 'Prepare brief',
    menu: 'Menu',
    language: 'Language',
    backTop: 'Back to top',
    home: 'Home',
    privacy: 'Privacy',
    footerLine: 'Business process improvement through controlled digital workflows.',
    footerIndex: 'Explore',
    footerLanguages: 'Languages',
    footerNote: 'Optimix · 2026',
    previous: 'Previous step', next: 'Next step',
  },
  hero: {
    lines: ['Every handoff', 'should move work', 'forward.'],
    intro: 'Optimix helps growing teams turn repeated manual handoffs into controlled workflows. Systems handle routine steps; people retain approvals and exceptions.',
    secondary: 'See a process example',
    previewLabel: 'Illustrative procurement sequence',
    preview: ['Request received', 'Rules checked', 'Person approves', 'Decision recorded'],
    credit: 'Concept image for design evaluation. Not a client project.',
    artAlt: 'Illustrative procurement desk with people reviewing documents; generated concept image, not an Optimix client project.',
  },
  quotes: {
    first: 'Routine steps move. People decide.',
  },
  problem: {
    title: 'The work moves. The context does not.',
    lead: 'One request can pass through several tools and inboxes. Each transfer creates another place to wait, copy or ask for status.',
    relay: [
      { title: 'Request by email', detail: 'A request arrives outside the process.', insight: 'The next owner has no shared record of when it entered the route.', response: 'A common intake could capture the received time, required fields and the person responsible.' },
      { title: 'Budget in a file', detail: 'The same details are entered again.', insight: 'A second copy can drift from the original request as documents change.', response: 'One source of request data could feed the budget check without another free-standing copy.' },
      { title: 'Approval in an inbox', detail: 'Status depends on a reply.', insight: 'The decision remains in a message until someone transfers it.', response: 'An approval could record who decided, when and why, then route the request onward.' },
      { title: 'Order in the ERP', detail: 'Approved data is copied once more.', insight: 'Reviewed information becomes another manual entry point.', response: 'Approved fields could pass to the ERP, with mismatches returned for a person to review.' },
      { title: 'Status by email', detail: 'People ask where the request stands.', insight: 'Visibility depends on asking someone rather than seeing a recorded state.', response: 'A visible state could show the current owner and next action without another status email.' },
    ],
    note: 'Illustrative pattern, not a description of a client’s operation.',
    relayLabel: 'Illustrative manual purchase request relay',
    swipeHint: 'Swipe to follow the handoffs',
    explore: 'What could change', close: 'Close detail',
  },
  change: {
    title: 'Make the route explicit before automating it.',
    lead: 'The aim is a process people can follow, question and measure, across the systems already in use.',
    rows: [
      { title: 'See the actual handoffs.', detail: 'Identify inputs, owners, approvals, repeated entry and where work waits.' },
      { title: 'Connect repeatable steps.', detail: 'Use rules and validation to move routine work through existing tools where appropriate.' },
      { title: 'Keep decisions accountable.', detail: 'Send ambiguous cases and exceptions to the right person, and record what happened.' },
    ],
    before: 'Before: fragmented handoffs',
    beforeSteps: ['Email request', 'Copy to spreadsheet', 'Wait for approval', 'Re-enter in ERP', 'Ask for status'],
    after: 'After: controlled route',
    afterSteps: ['Input', 'Validate', 'Route', 'Human decision', 'Execute', 'Record'],
    afterNote: 'Exceptions return to a person. The actual route depends on the organisation.',
    compareLabel: 'Compare the current and proposed route',
    beforeTab: 'Before',
    afterTab: 'After',
  },
  workflow: {
    title: 'Follow one request.',
    lead: 'A purchase request gives the route a concrete shape: input, validation, human decisions, system actions and a recorded outcome.',
    disclosure: 'Illustrative reference flow. It is not a client case or a verified depiction of Optimix’s existing demonstration. Actual steps depend on the organisation.',
    human: 'Human',
    system: 'System',
    checkpoint: 'Checkpoint',
    routePosition: 'Route position',
    bottomline: 'A failed check should lead to a decision, not a silent handoff.',
    steps: [
      { role: 'Human', note: 'Input', title: 'Request submitted', detail: 'A person supplies the need, owner and supporting information.' },
      { role: 'System', note: 'Validation', title: 'Budget checked', detail: 'Defined rules check the request before it moves forward.' },
      { role: 'Human', note: 'Approval', title: 'Manager decision', detail: 'An authorised person approves, declines or asks for a change.' },
      { role: 'Human', note: 'Decision', title: 'Supplier selected', detail: 'Judgement stays with the person responsible for the purchase.' },
      { role: 'System', note: 'Output', title: 'Purchase order recorded', detail: 'Approved information can pass into the existing ERP.' },
      { role: 'System', note: 'Waiting', title: 'Await shipment; update stock', detail: 'The route pauses until delivery information arrives, then updates inventory.' },
      { role: 'System', note: 'Validation', title: 'Invoice checked', detail: 'Documents are checked against the order; mismatches need review.' },
      { role: 'System', note: 'Completed', title: 'KPI / SLA record updated', detail: 'The completed route leaves a trace for later review.' },
    ],
    exceptionLabel: 'Exception / human review',
    exceptionDetail: 'If budget or information fails a check, the request pauses. A manager reviews the issue, records a decision and either returns it to the route or stops it.',
    routeHint: 'Scroll to follow the route',
  },
  value: {
    title: 'The case has to work on paper, too.',
    lead: 'A useful estimate starts with the work as it happens today and the full cost of changing it.',
    modelLabel: 'Business value and change cost considered together',
    upsideTitle: 'Value at stake',
    upside: [
      { title: 'Repeated handling', detail: 'How often the work happens, how long each pass takes and whose time it uses.' },
      { title: 'Operational friction', detail: 'Errors, waiting and the effort needed to manage greater volume.' },
    ],
    investmentTitle: 'Cost to change',
    investment: [
      { title: 'Build and connect', detail: 'Implementation and integration with the systems already in use.' },
      { title: 'Adopt and maintain', detail: 'Training, upkeep and clear ownership of the new process.' },
    ],
    decision: 'The decision',
    decisionQuestion: 'Is the measurable value greater than the cost and risk of changing the process?',
    footnote: 'Time released is capacity. It becomes a cash saving only when the business can actually reduce cost or redeploy that capacity. Any estimate needs the company’s own baseline.',
  },
  approach: {
    title: 'Start with the process, then choose the mechanism.',
    lead: 'A sensible engagement would begin by observing the work, agreeing where control belongs, and testing whether the proposed change is worth maintaining.',
    note: 'Proposed approach, not a fixed delivery promise.',
    stages: [
      { title: 'Understand', detail: 'Observe inputs, people, systems, documents and exceptions.' },
      { title: 'Map', detail: 'Make handoffs, waiting and repeated entry visible.' },
      { title: 'Decide', detail: 'Agree which steps stay with people and where approval belongs.' },
      { title: 'Build', detail: 'Connect a limited repeatable route where the environment permits.' },
      { title: 'Measure', detail: 'Compare the new route with the original baseline.' },
      { title: 'Improve', detail: 'Refine rules from actual operation and recorded exceptions.' },
    ],
  },
  contactTeaser: {
    title: 'Bring one process.',
    lead: 'Describe the repeated work, who takes part, which tools it crosses and where it stalls. That is enough to begin a useful assessment of whether changing it makes economic sense.',
    cta: 'Prepare a process brief',
    status: 'Download a draft brief to use later. This site does not accept inquiries yet.',
  },
  contactPage: {
    title: 'Start with one process.',
    lead: 'A technical specification is not needed. Describe the work, the people involved and where the route slows down.',
    status: 'Prepare a process brief you can save on your device. Nothing you enter here is sent to Optimix.',
    details: 'The inquiry channel is not configured yet. Do not include confidential documents or sensitive personal information.',
    builderTitle: 'Your process brief',
    builderIntro: 'Use the prompts below to draft the essentials. You can leave fields blank and complete the file later.',
    process: 'Process name',
    description: 'Describe the process',
    systems: 'Current systems',
    problem: 'Main problem or bottleneck',
    frequency: 'Approximate frequency',
    download: 'Download draft brief',
    downloadNotice: 'Your browser should download the draft. Nothing was sent to Optimix.',
    privacyLink: 'Privacy information',
  },
  privacyPage: {
    title: 'Privacy information is being prepared.',
    lead: 'The brief builder creates a text file in your browser. This site does not submit the fields you enter to Optimix.',
    detail: 'The inquiry channel is not active. The legal operator, contact, processing purposes, recipients, retention period and applicable rights will be published after they are confirmed. This page is not a final privacy notice.',
    back: 'Return to the process brief',
  },
};
