import type { Locale } from './index';

export function homeRedesign(locale: Locale) {
  const s = (ru: string, en: string, ro: string) => ({ ru, en, ro })[locale];
  return {
    nav: [s('Направления','Services','Direcții'),s('Примеры','Examples','Exemple'),s('Как начать','Getting started','Cum începem'),s('Вопросы','Questions','Întrebări')],
    menu: s('Меню','Menu','Meniu'), brief: s('Бриф','Brief','Brief'),
    action: s('Описать задачу','Describe your task','Descrie sarcina'), example: s('Посмотреть пример','See an example','Vezi un exemplu'),
    eyebrow: s('Автоматизация бизнес-процессов','Business process automation','Automatizarea proceselor de afaceri'),
    title: [s('Автоматизируем процессы.','Automate your processes.','Automatizăm procesele.'),s('Ускоряем ваш бизнес.','Move your business forward.','Accelerăm afacerea.')],
    intro: s('HR, документы, CRM, ERP, закупки, прогнозирование и аналитика — помогаем убрать ручную работу и связать процессы, людей и системы.','HR, documents, CRM, ERP, procurement, forecasting and analytics — we help reduce manual work and connect processes, people and systems.','HR, documente, CRM, ERP, achiziții, prognoză și analiză — reducem munca manuală și conectăm procesele, oamenii și sistemele.'),
    localNote: s('Подготовьте бриф и сохраните его на устройстве.','Prepare a brief and save it on your device.','Pregătește un brief și salvează-l pe dispozitiv.'),
    savedNote: s('Бриф сохраняется на вашем устройстве','Your brief is saved on your device','Brief-ul se salvează pe dispozitivul tău'),
    demoLabel: s('Демонстрационный сценарий','Demonstration scenario','Scenariu demonstrativ'),
    processLabel: s('Пример процесса','Process example','Exemplu de proces'),
    purchaseTitle: s('Заявка на закупку','Purchase request','Cerere de achiziție'),
    purchaseCaption: s('Пример автоматизации закупочной заявки','Purchase request automation example','Exemplu de automatizare a unei cereri de achiziție'),
    sceneNav: [s('Главная','Home','Acasă'),s('Заявки','Requests','Cereri'),s('Задачи','Tasks','Sarcini'),s('Документы','Documents','Documente'),s('Согласования','Approvals','Aprobări'),s('Аналитика','Analytics','Analiză'),s('Настройки','Settings','Setări')],
    initiator: s('Инициатор','Requester','Solicitant'),owner:s('Ответственный','Owner','Responsabil'),
    newRequest:s('Новый запрос','New request','Cerere nouă'),profile:s('Профиль отдела','Department profile','Profilul departamentului'),
    department:s('Подразделение','Department','Departament'),purchasing:s('Закупки','Procurement','Achiziții'),date:s('Дата создания','Created on','Data creării'),
    description:s('Описание','Description','Descriere'),
    requestDescription:s('Закупка офисного оборудования для нового подразделения.','Office equipment procurement for a new department.','Achiziția echipamentelor de birou pentru un departament nou.'),
    attachments:s('Прикрепленные документы','Attached documents','Documente atașate'),
    filenames:[s('Спецификация.pdf','Specification.pdf','Specificație.pdf'),s('Коммерческое предложение.pdf','Quotation.pdf','Ofertă.pdf'),s('Обоснование.docx','Justification.docx','Justificare.docx')],
    approval:s('Согласование','Approval','Aprobare'),
    stages:[s('Заявка','Request','Cerere'),s('Бюджет','Budget','Buget'),s('Согласование','Approval','Aprobare'),'ERP',s('Статус','Status','Stare')],
    states:[s('Подготовка','Prepared','Pregătită'),s('Проверено','Checked','Verificat'),s('На согласовании','Awaiting approval','În aprobare'),s('Ожидает','Waiting','În așteptare'),s('Ожидает','Waiting','În așteptare')],
    approveAction:s('Подтвердить и передать дальше','Confirm and move forward','Confirmă și continuă'),
    servicesTitle:s('Автоматизация там, где работает ваш бизнес','Automation wherever your business works','Automatizare acolo unde lucrează afacerea ta'),
    servicesIntro:s('От отдельной операции до связанной системы','From a single operation to a connected system','De la o operație la un sistem conectat'),
    learn:s('Узнать больше','Learn more','Află mai multe'),
    services:[
      {icon:'users',title:s('HR и команда','HR and teams','HR și echipă'),description:s('Автоматизация кадровых процессов и внутренних запросов.','Automate HR processes and internal requests.','Automatizarea proceselor HR și a cererilor interne.'),anchor:'people-documents'},
      {icon:'file-text',title:s('Документы и согласования','Documents and approvals','Documente și aprobări'),description:s('Единые маршруты и контроль на всех этапах.','Consistent workflows and oversight at every stage.','Trasee comune și control în fiecare etapă.'),anchor:'people-documents'},
      {icon:'chart-bar',title:s('CRM и продажи','CRM and sales','CRM și vânzări'),description:s('Связанные процессы от лида до сделки.','Connected processes from lead to deal.','Procese conectate de la lead la tranzacție.'),anchor:'business-systems'},
      {icon:'gear',title:s('ERP и операции','ERP and operations','ERP și operațiuni'),description:s('Интеграция и сквозные процессы в операциях.','Integration and connected operational processes.','Integrare și procese operaționale conectate.'),anchor:'business-systems'},
      {icon:'shopping-cart',title:s('Закупки и прогнозирование','Procurement and forecasting','Achiziții și prognoză'),description:s('Планирование, закупки и управление запасами.','Planning, procurement and inventory management.','Planificare, achiziții și gestionarea stocurilor.'),anchor:'planning-analytics'},
      {icon:'chart-line-up',title:s('Аналитика и контроль','Analytics and oversight','Analiză și control'),description:s('Данные для принятия решений и прозрачный контроль.','Data for decisions and transparent oversight.','Date pentru decizii și control transparent.'),anchor:'planning-analytics'},
    ],
    other:s('Не нашли свой процесс?','Have another process in mind?','Nu ai găsit procesul tău?'),
    scenes:[
      {id:'people-documents',title:s('Заявки, документы и решения — в понятном маршруте','Requests, documents and decisions — in a clear workflow','Cereri, documente și decizii — într-un traseu clar'),description:s('Структурируем процесс, собираем нужные данные и подсказываем следующий шаг для каждого участника.','Structure the process, collect the right data and show each participant the next step.','Structurăm procesul, colectăm datele necesare și arătăm pasul următor fiecărui participant.'),checks:[s('Нужные сведения собраны','The right information is collected','Informațiile necesare sunt colectate'),s('Следующая задача назначена','The next task is assigned','Următoarea sarcină este atribuită'),s('Статус доступен команде','The team can see the status','Starea este vizibilă pentru echipă')]},
      {id:'business-systems',title:s('Данные движутся между командами и системами','Data moves between teams and systems','Datele circulă între echipe și sisteme'),description:s('Связываем людей, процессы и системы, чтобы информация не терялась и не дублировалась.','Connect people, processes and systems so information is neither lost nor duplicated.','Conectăm oamenii, procesele și sistemele, pentru ca informațiile să nu se piardă sau să se dubleze.'),checks:[s('Единый контекст','Shared context','Context comun'),s('Меньше повторного ввода','Less repeated data entry','Mai puțină introducere repetată'),s('Понятный владелец исключения','A clear owner for exceptions','Responsabil clar pentru excepții')]},
      {id:'planning-analytics',title:s('От истории операций — к плану действий','From operational history to an action plan','De la istoricul operațiunilor la un plan de acțiune'),description:s('Используем данные из систем, чтобы формировать понятный план и вовремя реагировать на изменения.','Use data from your systems to build a clear plan and respond to changes in time.','Folosim datele din sisteme pentru un plan clar și reacții la timp la schimbări.'),checks:[s('Согласованные исходные данные','Agreed source data','Date inițiale aliniate'),s('Видимые допущения','Visible assumptions','Ipoteze vizibile'),s('Сравнение прогноза с фактом','Forecast compared with actuals','Compararea prognozei cu rezultatele')]},
    ],
    checksTitle:s('Проверка данных','Data checks','Verificarea datelor'),
    checks:[s('Основная информация','Core information','Informații de bază'),s('Бюджет и обоснование','Budget and justification','Buget și justificare'),s('Прикрепленные документы','Attached documents','Documente atașate'),s('Согласование','Approval','Aprobare')],
    intakeNav:[s('Данные заявки','Request data','Datele cererii'),s('Участники','Participants','Participanți'),s('Маршрут','Workflow','Traseu'),s('Документы','Documents','Documente'),s('История','History','Istoric')],
    departments:[s('Инициатор','Requester','Solicitant'),s('Финансовый отдел','Finance department','Departament financiar'),s('Юридический отдел','Legal department','Departament juridic'),s('Закупки','Procurement','Achiziții')],
    deal:s('Сделка','Deal','Tranzacție'),order:s('Заказ','Order','Comandă'),client:s('Клиент','Customer','Client'),
    demoCompany:s('ООО Ромашка','Example Co.','Compania exemplu'),inProgress:s('В работе','In progress','În lucru'),
    sync:s('Синхронизация данных','Data synchronization','Sincronizarea datelor'),orderNumber:s('Номер заказа','Order number','Numărul comenzii'),creating:s('Создаётся','Being created','Se creează'),processing:s('В обработке','Processing','În procesare'),
    planning:s('Планирование закупок','Procurement planning','Planificarea achizițiilor'),
    planTabs:[s('Товары','Products','Produse'),s('Прогноз','Forecast','Prognoză'),s('Фактические поставки','Actual deliveries','Livrări efective')],
    tableHeads:[s('Товар','Product','Produs'),s('Текущий запас','Current stock','Stoc curent'),s('Прогноз','Forecast','Prognoză'),s('План закупки','Purchase plan','Plan de achiziții'),s('Статус','Status','Stare')],
    products:[s('Ноутбук','Laptop','Laptop'),s('Монитор','Monitor','Monitor'),s('Клавиатура','Keyboard','Tastatură'),s('Мышь','Mouse','Mouse')],
    planned:s('В плане','Planned','Planificat'),attention:s('Требует внимания','Needs attention','Necesită atenție'),
    workflowTitle:[s('Рутина движется автоматически.','Routine moves automatically.','Rutina avansează automat.'),s('Решения остаются под контролем.','Decisions stay under control.','Deciziile rămân sub control.')],
    exception:s('Нет кода бюджета — проверка ответственным','Missing budget code — owner review','Lipsește codul bugetului — verifică responsabilul'),
    demoAction:s('Посмотреть демо закупки','Explore the procurement demo','Vezi demonstrația de achiziții'),
    valueTitle:s('Результат начинается с понимания процесса','Results begin with understanding the process','Rezultatul începe cu înțelegerea procesului'),
    values:[
      {icon:'clock',title:s('Время выполнения','Completion time','Timp de execuție'),description:s('Убираем лишние шаги и ускоряем согласования.','Remove unnecessary steps and speed up approvals.','Eliminăm pașii inutili și accelerăm aprobările.')},
      {icon:'file-text',title:s('Ручные действия и ошибки','Manual work and errors','Muncă manuală și erori'),description:s('Автоматизируем рутину и снижаем риск ошибок.','Automate routine work and reduce the risk of errors.','Automatizăm rutina și reducem riscul erorilor.')},
      {icon:'eye',title:s('Прозрачность и ответственность','Visibility and responsibility','Transparență și responsabilitate'),description:s('Видно, кто за что отвечает и на каком этапе процесс.','See who owns each task and where the process stands.','Se vede cine răspunde și în ce etapă este procesul.')},
    ],
    startTitle:s('Как начать','Getting started','Cum începem'),startIntro:s('Достаточно описать задачу, людей и системы.','Describe the task, people and systems.','Descrie sarcina, oamenii și sistemele.'),
    steps:[
      {title:s('Опишите процесс','Describe the process','Descrie procesul'),description:s('Расскажите, что нужно автоматизировать.','Tell us what needs to be automated.','Spune-ne ce trebuie automatizat.')},
      {title:s('Определите приоритет','Set the priority','Stabilește prioritatea'),description:s('Выберем подходящий сценарий.','Choose a suitable scenario.','Alegem scenariul potrivit.')},
      {title:s('Проверьте решение','Test the solution','Verifică soluția'),description:s('Покажем пример на ваших данных.','Explore an example using your data.','Arătăm un exemplu cu datele tale.')},
      {title:s('Оцените результат','Evaluate the result','Evaluează rezultatul'),description:s('Запустим и расширим на другие процессы.','Launch and extend to other processes.','Lansăm și extindem la alte procese.')},
    ],
    systemsTitle:s('Работаем в контексте ваших систем','Working in the context of your systems','Lucrăm în contextul sistemelor tale'),
    systemsIntro:s('Состав решения определяется задачей и доступными данными.','The task and available data determine the solution.','Sarcina și datele disponibile determină soluția.'),
    systems:['CRM','ERP',s('Документы','Documents','Documente'),s('Таблицы','Spreadsheets','Tabele'),s('HR-системы','HR systems','Sisteme HR'),s('Источники данных','Data sources','Surse de date')],
    faqTitle:s('Вопросы перед стартом','Questions before getting started','Întrebări înainte de start'),
    faqIntro:s('Короткие ответы на частые вопросы. Если не нашли нужный — опишите задачу.','Short answers to common questions. If yours is missing, describe your task.','Răspunsuri scurte la întrebări frecvente. Dacă nu ai găsit răspunsul, descrie sarcina.'),
    faqs:[
      {question:s('С какого процесса лучше начать?','Which process should we start with?','Cu ce proces începem?'),answer:s('С повторяющейся задачи с понятными входными данными и ответственным. Опишите текущие шаги, где возникает ручная работа и что хотите улучшить.','Start with a recurring task with clear inputs and an owner. Describe the steps, manual work and the improvement you want.','Începe cu o sarcină repetitivă, date clare și un responsabil. Descrie pașii, munca manuală și îmbunătățirea dorită.')},
      {question:s('Можно ли улучшить существующую CRM или ERP?','Can we improve an existing CRM or ERP?','Putem îmbunătăți un CRM sau ERP existent?'),answer:s('Да. Начинаем с задачи и возможностей вашей системы: доступных данных, способов обмена и правил доступа. Подход выбираем после разбора процесса.','Yes. We begin with your task and the capabilities of your system: available data, exchange methods and permissions. The process review determines the approach.','Da. Pornim de la sarcină și posibilitățile sistemului: date, metode de schimb și acces. Alegem abordarea după analiza procesului.')},
      {question:s('Можно ли автоматизировать часть процесса?','Can we automate part of a process?','Putem automatiza doar o parte a procesului?'),answer:s('Да. Можно начать с отдельной операции, проверить решение и постепенно связать его с другими этапами. Решения и исключения остаются у ответственных.','Yes. Start with one operation, verify the solution and gradually connect it to other stages. Owners retain decisions and exceptions.','Da. Începem cu o operație, verificăm soluția și o conectăm treptat la alte etape. Deciziile și excepțiile rămân la responsabili.')},
      {question:s('Какие данные нужны для прогнозирования?','What data is needed for forecasting?','Ce date sunt necesare pentru prognoză?'),answer:s('Зависит от задачи. Обычно нужны история операций, текущие остатки или состояния и известные ограничения. Сначала оцениваем полноту данных и фиксируем допущения.','It depends on the task. Usually operational history, current inventory or states, and known constraints are needed. First assess data completeness and record assumptions.','Depinde de sarcină. De obicei sunt necesare istoricul operațiunilor, stocurile sau stările curente și constrângerile. Evaluăm datele și documentăm ipotezele.')},
      {question:s('Что подготовить для обсуждения?','What should we prepare for a discussion?','Ce pregătim pentru discuție?'),answer:s('Краткое описание процесса, его участников, используемых систем и желаемого изменения. На странице брифа можно собрать сведения и сохранить их текстовым файлом на своём устройстве.','A short description of the process, participants, systems and desired change. The brief page helps you collect this information and save it as a text file on your device.','O descriere a procesului, participanților, sistemelor și schimbării dorite. Pagina de brief te ajută să salvezi informațiile într-un fișier text pe dispozitiv.')},
    ],
    finalTitle:s('Начните с процесса, который хотите улучшить','Start with the process you want to improve','Începe cu procesul pe care vrei să-l îmbunătățești'),
    finalIntro:s('Опишите работу команды — подготовьте бриф задачи','Describe how your team works — prepare a task brief','Descrie munca echipei — pregătește un brief'),
    privacy:s('Конфиденциальность','Privacy','Confidențialitate'),
  };
}
