import type { Locale } from './index';

export const moduleSlugs = ['intake', 'budget', 'approval', 'erp', 'visibility'] as const;
export type ModuleSlug = typeof moduleSlugs[number];

type ModuleCopy = {
  slug: ModuleSlug;
  title: string;
  manual: string;
  proposal: string;
  human: string;
  technology: string;
  input: string;
  rule: string;
  exception: string;
  output: string;
};

type PortfolioCopy = {
  hero: { eyebrow: string; title: string; intro: string; primary: string; secondary: string; visualLabel: string; visualNote: string; graphLabel: string; signals: string[]; stages: string[] };
  workflow: { eyebrow: string; title: string; intro: string; manual: string; proposal: string; human: string; details: string; disclosure: string };
  proof: { title: string; intro: string; items: { title: string; detail: string }[] };
  method: { title: string; items: { title: string; detail: string }[] };
  contact: { title: string; intro: string; action: string; note: string };
  detail: { eyebrow: string; current: string; proposed: string; responsibility: string; mechanism: string; input: string; rule: string; exception: string; output: string; demo: string; back: string; next: string; disclosure: string };
  project: { eyebrow: string; title: string; intro: string; statusTitle: string; status: string; prerequisitesTitle: string; prerequisites: string[]; modulesTitle: string; moduleLink: string; demoLink: string; projectLink: string };
  demo: { title: string; intro: string; kicker: string; scenarioLabel: string; normal: string; exception: string; next: string; resolve: string; restart: string; active: string; complete: string; halted: string; disclosure: string; current: string; proposed: string };
  modules: ModuleCopy[];
};

export const portfolio: Record<Locale, PortfolioCopy> = {
  en: {
    hero: { eyebrow: 'One process · five handoffs', title: 'See how to reduce manual handoffs in purchasing.', intro: 'See where a request is copied, checked, approved and entered again. Each step shows a possible automation and the decision that remains with a person.', primary: 'Explore the workflow', secondary: 'Try the process demo', visualLabel: 'Interactive illustration of a purchase request route', visualNote: 'Directional illustration, not measured client results.', graphLabel: 'Five handoffs / model', signals: ['Less re-entry', 'Visible ownership', 'Recorded decisions'], stages: ['Intake', 'Budget', 'Approval', 'ERP', 'Status'] },
    workflow: { eyebrow: 'Illustrative procurement route', title: 'One workflow. Five changes you can inspect.', intro: 'Choose a handoff to see the proposed mechanism, required inputs and exception handling on its own page.', manual: 'Today', proposal: 'Proposed', human: 'Human control', details: 'Open module', disclosure: 'Conceptual example, not a client case or a verified description of the existing Optimix demo. Integration depends on the organisation’s systems.' },
    proof: { title: 'Measure the process before claiming a result.', intro: 'The demo shows how a route could work. A real business case needs the current baseline and integration constraints.', items: [{ title: 'Handling time', detail: 'Count manual touches and waiting time for each request.' }, { title: 'Exceptions', detail: 'Track missing data, mismatches and who resolves them.' }, { title: 'Change cost', detail: 'Include integration, adoption and ongoing ownership.' }] },
    method: { title: 'How a real project would start', items: [{ title: 'Map the actual route', detail: 'Identify inputs, systems, owners and approval points.' }, { title: 'Test one repeatable step', detail: 'Validate a limited change against real exceptions.' }, { title: 'Compare with baseline', detail: 'Check time, quality and upkeep before expanding.' }] },
    contact: { title: 'Bring a process you want to improve.', intro: 'Record the handoffs, systems and recurring delays. You can download a brief and complete it later.', action: 'Prepare a process brief', note: 'The site does not accept inquiries yet.' },
    detail: { eyebrow: 'Procurement example · module', current: 'Manual handoff', proposed: 'Proposed change', responsibility: 'Person remains responsible', mechanism: 'How it could work', input: 'Input', rule: 'System action', exception: 'Exception path', output: 'Recorded result', demo: 'Open interactive demo', back: 'All modules', next: 'Next module', disclosure: 'Illustrative design pattern. No client result or live integration is claimed.' },
    project: { eyebrow: 'Portfolio outline / illustrative', title: 'Procurement request route', intro: 'A proposed route that connects request intake, budget validation, approval, ERP transfer and status visibility. The module pages describe the mechanics; the browser demo shows the sequence and one exception.', statusTitle: 'Current status', status: 'Concept only. The existing Optimix demonstration has not been verified here; no client deployment, integration or measured result is represented.', prerequisitesTitle: 'Needed for a real project', prerequisites: ['The actual request fields, approval rules and exception owners.', 'Access to the approved budget source and ERP interface.', 'A baseline for handling time, errors and support cost.'], modulesTitle: 'Explore the five modules', moduleLink: 'Open module', demoLink: 'Try the interactive demo', projectLink: 'Project outline' },
    demo: { title: 'Walk through a purchase request.', intro: 'A local simulation of the proposed route. Choose complete data or an exception and advance through the five handoffs.', kicker: 'Procurement route / interactive example', scenarioLabel: 'Choose a scenario', normal: 'Complete data', exception: 'Missing budget code', next: 'Next step', resolve: 'Record human review and continue', restart: 'Start again', active: 'Current step', complete: 'Route completed. Every handoff has a recorded state.', halted: 'The budget check has stopped the route for a person to review.', disclosure: 'Illustrative browser-only demo. It does not connect to an ERP, submit data or represent a verified client project.', current: 'Manual route', proposed: 'Proposed route' },
    modules: [
      { slug: 'intake', title: 'Capture the request once', manual: 'A purchase request arrives by email without shared fields or an owner.', proposal: 'A structured intake records the request, required fields and receiving time.', human: 'A requester describes the business need and confirms the submitted details.', technology: 'Structured intake with required-field validation', input: 'Need, requester, cost centre and supporting information.', rule: 'Check required fields and create a single request record.', exception: 'Return an incomplete request to its owner with the missing fields listed.', output: 'A timestamped request with an owner and one reference.' },
      { slug: 'budget', title: 'Check the budget from one record', manual: 'The same amounts and codes are copied into a separate budget file.', proposal: 'Defined rules compare the request with the approved budget source.', human: 'A budget owner reviews missing codes or requests outside the rule.', technology: 'Rule-based validation against an approved budget source', input: 'Request amount, cost centre, budget code and current allowance.', rule: 'Validate the code and compare the amount with the allowed balance.', exception: 'Pause the route when data is absent or outside the approved rule.', output: 'A pass or review state attached to the request.' },
      { slug: 'approval', title: 'Record the approval decision', manual: 'A decision sits in an inbox until somebody forwards it.', proposal: 'A named approver receives context and records approve, reject or return.', human: 'The authorised approver makes the actual business decision.', technology: 'Role-based approval queue with an audit trail', input: 'Validated request, supporting files and approval policy.', rule: 'Route to the assigned approver and record the chosen action.', exception: 'Escalate an absent approver or return a request needing clarification.', output: 'Decision, person, time and reason in the request history.' },
      { slug: 'erp', title: 'Transfer approved data to ERP', manual: 'Approved fields are typed into the ERP again.', proposal: 'A controlled mapping transfers only approved fields and checks the response.', human: 'An operator reviews rejected records and mismatched values.', technology: 'Validated field mapping and ERP interface', input: 'Approved request, supplier and order fields.', rule: 'Map allowed fields to the ERP and confirm an order reference.', exception: 'Stop and show the rejected field if the ERP does not accept the record.', output: 'ERP reference linked to the approved request.' },
      { slug: 'visibility', title: 'Show the next owner and state', manual: 'People ask by email where the request stands.', proposal: 'A shared status view shows the current state, owner and next action.', human: 'Owners update decisions or resolve stalled exceptions.', technology: 'State history and role-aware status view', input: 'Events from intake, checks, approval and ERP.', rule: 'Update the state when a recorded event changes the route.', exception: 'Flag a stalled or inconsistent state for its owner.', output: 'A traceable timeline and clear next action.' },
    ],
  },
  ro: {
    hero: { eyebrow: 'Un proces · cinci transferuri', title: 'Vezi cum reduci transferurile manuale în achiziții.', intro: 'Vezi unde o cerere este copiată, verificată, aprobată și introdusă din nou. Fiecare pas arată o posibilă automatizare și decizia care rămâne la o persoană.', primary: 'Explorează fluxul', secondary: 'Încearcă demonstrația', visualLabel: 'Ilustrație interactivă a traseului unei cereri de achiziție', visualNote: 'Ilustrație orientativă, nu rezultate măsurate la clienți.', graphLabel: 'Cinci transferuri / model', signals: ['Mai puțină reintroducere', 'Responsabil vizibil', 'Decizii înregistrate'], stages: ['Intrare', 'Buget', 'Aprobare', 'ERP', 'Status'] },
    workflow: { eyebrow: 'Traseu ilustrativ de achiziții', title: 'Un singur flux. Cinci schimbări de analizat.', intro: 'Alege un transfer pentru a vedea mecanismul propus, datele necesare și gestionarea excepțiilor pe o pagină separată.', manual: 'În prezent', proposal: 'Propus', human: 'Control uman', details: 'Deschide modulul', disclosure: 'Exemplu conceptual, nu caz al unui client sau descriere verificată a demonstrației Optimix existente. Integrarea depinde de sistemele organizației.' },
    proof: { title: 'Măsoară procesul înainte de a promite un rezultat.', intro: 'Demonstrația arată cum ar putea funcționa traseul. Un calcul real are nevoie de situația inițială și de constrângerile de integrare.', items: [{ title: 'Timp de prelucrare', detail: 'Numără intervențiile manuale și așteptarea pentru fiecare cerere.' }, { title: 'Excepții', detail: 'Urmărește datele lipsă, neconcordanțele și cine le rezolvă.' }, { title: 'Costul schimbării', detail: 'Include integrarea, adoptarea și responsabilitatea continuă.' }] },
    method: { title: 'Cum ar începe un proiect real', items: [{ title: 'Cartografiază traseul actual', detail: 'Identifică datele, sistemele, responsabilii și aprobările.' }, { title: 'Testează un pas repetabil', detail: 'Verifică o schimbare limitată folosind excepții reale.' }, { title: 'Compară cu situația inițială', detail: 'Verifică timpul, calitatea și întreținerea înainte de extindere.' }] },
    contact: { title: 'Adu un proces pe care vrei să îl îmbunătățești.', intro: 'Notează transferurile, sistemele și întârzierile repetate. Poți descărca o descriere pentru a o completa ulterior.', action: 'Pregătește descrierea', note: 'Site-ul nu primește încă cereri.' },
    detail: { eyebrow: 'Exemplu de achiziții · modul', current: 'Transfer manual', proposed: 'Schimbare propusă', responsibility: 'Responsabilitatea persoanei', mechanism: 'Cum ar putea funcționa', input: 'Date de intrare', rule: 'Acțiunea sistemului', exception: 'Traseul excepției', output: 'Rezultat înregistrat', demo: 'Deschide demonstrația', back: 'Toate modulele', next: 'Modulul următor', disclosure: 'Model ilustrativ. Nu sunt revendicate rezultate la clienți sau integrări active.' },
    project: { eyebrow: 'Schiță de portofoliu / ilustrativă', title: 'Traseul cererii de achiziție', intro: 'Un traseu propus care leagă înregistrarea cererii, verificarea bugetului, aprobarea, transferul în ERP și vizibilitatea statusului. Paginile modulelor explică mecanismele; demonstrația în browser arată secvența și o excepție.', statusTitle: 'Stadiul actual', status: 'Doar concept. Demonstrația Optimix existentă nu a fost verificată aici; nu sunt prezentate implementări la clienți, integrări sau rezultate măsurate.', prerequisitesTitle: 'Necesare pentru un proiect real', prerequisites: ['Câmpurile reale ale cererii, regulile de aprobare și responsabilii excepțiilor.', 'Acces la sursa bugetară aprobată și la interfața ERP.', 'Situația inițială pentru timp, erori și costul întreținerii.'], modulesTitle: 'Explorează cele cinci module', moduleLink: 'Deschide modulul', demoLink: 'Încearcă demonstrația', projectLink: 'Schița proiectului' },
    demo: { title: 'Urmărește o cerere de achiziție.', intro: 'Simulare locală a traseului propus. Alege date complete sau o excepție și avansează prin cele cinci transferuri.', kicker: 'Traseu de achiziții / exemplu interactiv', scenarioLabel: 'Alege un scenariu', normal: 'Date complete', exception: 'Cod bugetar lipsă', next: 'Pasul următor', resolve: 'Înregistrează analiza umană și continuă', restart: 'Reia', active: 'Pasul curent', complete: 'Traseu încheiat. Fiecare transfer are o stare înregistrată.', halted: 'Verificarea bugetului a oprit traseul pentru analiza unei persoane.', disclosure: 'Demonstrație ilustrativă doar în browser. Nu se conectează la ERP, nu trimite date și nu reprezintă un proiect verificat al unui client.', current: 'Traseu manual', proposed: 'Traseu propus' },
    modules: [
      { slug: 'intake', title: 'Înregistrează cererea o singură dată', manual: 'Cererea sosește prin e-mail fără câmpuri comune sau responsabil.', proposal: 'O intrare structurată păstrează cererea, câmpurile obligatorii și ora primirii.', human: 'Solicitantul descrie nevoia și confirmă informațiile trimise.', technology: 'Intrare structurată cu verificarea câmpurilor obligatorii', input: 'Nevoia, solicitantul, centrul de cost și documentele suport.', rule: 'Verifică informațiile obligatorii și creează o singură înregistrare.', exception: 'Trimite cererea incompletă înapoi cu lista datelor lipsă.', output: 'Cerere cu dată, responsabil și referință unică.' },
      { slug: 'budget', title: 'Verifică bugetul din aceeași înregistrare', manual: 'Sumele și codurile sunt copiate într-un fișier bugetar separat.', proposal: 'Regulile definite compară cererea cu sursa bugetară aprobată.', human: 'Responsabilul bugetar analizează codurile lipsă și cazurile în afara regulilor.', technology: 'Validare pe bază de reguli cu sursa bugetară aprobată', input: 'Sumă, centru de cost, cod bugetar și disponibil.', rule: 'Validează codul și compară suma cu soldul permis.', exception: 'Oprește traseul când lipsesc date sau cererea depășește regula.', output: 'Stare de aprobare sau analiză atașată cererii.' },
      { slug: 'approval', title: 'Înregistrează decizia de aprobare', manual: 'Decizia rămâne în inbox până o transmite cineva.', proposal: 'Un aprobator desemnat primește contextul și înregistrează aprobarea, respingerea sau returnarea.', human: 'Persoana autorizată ia decizia de afaceri.', technology: 'Coadă de aprobări pe roluri cu jurnal de decizii', input: 'Cerere validată, documente și reguli de aprobare.', rule: 'Trimite către aprobator și înregistrează acțiunea aleasă.', exception: 'Escaladează absența aprobatorului sau cere clarificări.', output: 'Decizie, persoană, timp și motiv în istoricul cererii.' },
      { slug: 'erp', title: 'Transferă datele aprobate în ERP', manual: 'Câmpurile aprobate sunt introduse din nou în ERP.', proposal: 'O mapare controlată transferă doar câmpurile aprobate și verifică răspunsul.', human: 'Operatorul verifică înregistrările respinse și valorile neconcordante.', technology: 'Mapare validată a câmpurilor și interfață ERP', input: 'Cerere aprobată, furnizor și câmpuri pentru comandă.', rule: 'Mapează câmpurile permise și confirmă referința comenzii.', exception: 'Oprește transferul și arată câmpul respins de ERP.', output: 'Referință ERP legată de cererea aprobată.' },
      { slug: 'visibility', title: 'Arată responsabilul și starea următoare', manual: 'Oamenii întreabă prin e-mail unde se află cererea.', proposal: 'O vedere comună arată starea curentă, responsabilul și acțiunea următoare.', human: 'Responsabilii actualizează deciziile și rezolvă excepțiile.', technology: 'Istoric de stări și vedere pe roluri', input: 'Evenimente din intrare, verificări, aprobare și ERP.', rule: 'Actualizează starea la schimbarea înregistrată a traseului.', exception: 'Semnalează o stare blocată sau neconcordantă responsabilului.', output: 'Cronologie verificabilă și acțiune următoare clară.' },
    ],
  },
  ru: {
    hero: { eyebrow: 'Один процесс · пять передач', title: 'Показываем, как сократить ручные передачи в закупке.', intro: 'Разбираем, где заявку копируют, проверяют, согласуют и вводят заново. Для каждого шага — возможная автоматизация и решение, которое остаётся за человеком.', primary: 'Посмотреть маршрут', secondary: 'Открыть демо процесса', visualLabel: 'Интерактивная иллюстрация маршрута закупочной заявки', visualNote: 'Схема показывает направление изменений, а не измеренные результаты клиента.', graphLabel: 'Пять передач / модель', signals: ['Меньше повторного ввода', 'Видимый ответственный', 'Записанные решения'], stages: ['Приём', 'Бюджет', 'Согласование', 'ERP', 'Статус'] },
    workflow: { eyebrow: 'Иллюстративный маршрут закупки', title: 'Один маршрут. Пять конкретных изменений.', intro: 'Выберите передачу, чтобы на отдельной странице увидеть механизм, входные данные и работу с исключениями.', manual: 'Сейчас', proposal: 'Предлагаем', human: 'Решает человек', details: 'Открыть модуль', disclosure: 'Концептуальный пример, а не кейс клиента или проверенное описание существующего демо Optimix. Интеграция зависит от систем организации.' },
    proof: { title: 'Сначала измерить процесс, потом обещать результат.', intro: 'Демо показывает возможный маршрут. Для расчёта эффекта нужны исходные показатели и ограничения интеграции.', items: [{ title: 'Время обработки', detail: 'Считаем ручные действия и ожидание по каждой заявке.' }, { title: 'Исключения', detail: 'Фиксируем недостающие данные, расхождения и ответственного за решение.' }, { title: 'Стоимость изменений', detail: 'Учитываем интеграцию, внедрение и дальнейшее сопровождение.' }] },
    method: { title: 'Как начать реальный проект', items: [{ title: 'Описать текущий маршрут', detail: 'Уточнить входные данные, системы, роли и точки согласования.' }, { title: 'Проверить один повторяемый шаг', detail: 'Испытать ограниченное изменение на реальных исключениях.' }, { title: 'Сравнить с исходным состоянием', detail: 'Проверить время, качество и стоимость поддержки до расширения.' }] },
    contact: { title: 'Принесите процесс, который хотите улучшить.', intro: 'Запишите передачи, системы и повторяющиеся задержки. Черновик можно скачать и дополнить позже.', action: 'Подготовить описание процесса', note: 'Заявки на сайте пока не принимаются.' },
    detail: { eyebrow: 'Пример закупки · модуль', current: 'Ручная передача', proposed: 'Предлагаемое изменение', responsibility: 'Ответственность человека', mechanism: 'Как это может работать', input: 'Входные данные', rule: 'Действие системы', exception: 'Путь исключения', output: 'Записанный результат', demo: 'Открыть интерактивное демо', back: 'Все модули', next: 'Следующий модуль', disclosure: 'Иллюстративный сценарий. Здесь нет заявлений о результатах клиентов или действующей интеграции.' },
    project: { eyebrow: 'Страница портфолио / иллюстрация', title: 'Маршрут закупочной заявки', intro: 'Предлагаемый маршрут связывает приём заявки, проверку бюджета, согласование, передачу в ERP и видимость статуса. Страницы модулей объясняют механизмы; браузерное демо показывает последовательность и одно исключение.', statusTitle: 'Текущий статус', status: 'Пока это концепция. Существующая демонстрация Optimix здесь не проверена; внедрение у клиента, интеграция и измеренные результаты не представлены.', prerequisitesTitle: 'Что нужно для реального проекта', prerequisites: ['Фактические поля заявки, правила согласования и ответственные за исключения.', 'Доступ к утверждённому источнику бюджета и интерфейсу ERP.', 'Исходные данные о времени, ошибках и стоимости поддержки.'], modulesTitle: 'Пять модулей маршрута', moduleLink: 'Открыть модуль', demoLink: 'Открыть интерактивное демо', projectLink: 'Страница проекта' },
    demo: { title: 'Пройдите маршрут закупочной заявки.', intro: 'Локальная симуляция предлагаемого процесса. Выберите полные данные или исключение и пройдите пять передач.', kicker: 'Маршрут закупки / интерактивный пример', scenarioLabel: 'Выберите сценарий', normal: 'Полные данные', exception: 'Нет кода бюджета', next: 'Следующий шаг', resolve: 'Записать решение человека и продолжить', restart: 'Начать заново', active: 'Текущий шаг', complete: 'Маршрут завершён. У каждой передачи есть записанное состояние.', halted: 'Проверка бюджета остановила маршрут для решения человека.', disclosure: 'Иллюстративное демо только в браузере. Оно не подключено к ERP, не отправляет данные и не представляет проверенный проект клиента.', current: 'Ручной маршрут', proposed: 'Предлагаемый маршрут' },
    modules: [
      { slug: 'intake', title: 'Принять заявку один раз', manual: 'Заявка приходит по почте без общих полей и назначенного ответственного.', proposal: 'Структурированный ввод фиксирует заявку, обязательные поля и время получения.', human: 'Инициатор описывает потребность и подтверждает введённые сведения.', technology: 'Структурированный ввод с проверкой обязательных полей', input: 'Потребность, инициатор, центр затрат и сопроводительные сведения.', rule: 'Проверить обязательные поля и создать одну запись заявки.', exception: 'Вернуть неполную заявку владельцу со списком недостающих полей.', output: 'Заявка со временем получения, владельцем и единым номером.' },
      { slug: 'budget', title: 'Проверить бюджет по одной записи', manual: 'Суммы и коды повторно копируют в отдельный бюджетный файл.', proposal: 'Заданные правила сверяют заявку с утверждённым источником бюджета.', human: 'Ответственный за бюджет рассматривает отсутствие кода и выход за правило.', technology: 'Проверка по правилам с утверждённым источником бюджета', input: 'Сумма, центр затрат, код бюджета и доступный остаток.', rule: 'Проверить код и сопоставить сумму с доступным остатком.', exception: 'Остановить маршрут, если данных нет или заявка выходит за правило.', output: 'Статус проверки или рассмотрения в записи заявки.' },
      { slug: 'approval', title: 'Зафиксировать согласование', manual: 'Решение остаётся в почте, пока его кто-то не перешлёт.', proposal: 'Назначенный согласующий получает контекст и записывает одобрение, отказ или возврат.', human: 'Уполномоченный сотрудник принимает деловое решение.', technology: 'Очередь согласований по ролям с историей решений', input: 'Проверенная заявка, документы и правила согласования.', rule: 'Направить назначенному сотруднику и сохранить его действие.', exception: 'Передать дело другому ответственному или вернуть на уточнение.', output: 'Решение, сотрудник, время и причина в истории заявки.' },
      { slug: 'erp', title: 'Передать подтверждённые данные в ERP', manual: 'Одобренные поля ещё раз вводят вручную в ERP.', proposal: 'Контролируемое сопоставление передаёт только подтверждённые поля и проверяет ответ.', human: 'Оператор разбирает отклонённые записи и расхождения.', technology: 'Проверенное сопоставление полей и интерфейс ERP', input: 'Одобренная заявка, поставщик и поля заказа.', rule: 'Сопоставить разрешённые поля и подтвердить номер заказа.', exception: 'Остановить передачу и показать поле, которое ERP не приняла.', output: 'Номер в ERP, связанный с одобренной заявкой.' },
      { slug: 'visibility', title: 'Показать статус и следующего ответственного', manual: 'Участники спрашивают по почте, где находится заявка.', proposal: 'Общий статус показывает состояние, владельца и следующее действие.', human: 'Ответственные записывают решения и устраняют задержки.', technology: 'История состояний и просмотр по ролям', input: 'События приёма, проверок, согласования и ERP.', rule: 'Обновить состояние после записанного события маршрута.', exception: 'Отметить зависшую или противоречивую запись для ответственного.', output: 'Проверяемая история и ясное следующее действие.' },
    ],
  },
};

export function modulePath(locale: Locale, slug: ModuleSlug): string {
  return `${locale === 'en' ? '' : `/${locale}`}/solutions/${slug}/`;
}

export function demoPath(locale: Locale): string {
  return `${locale === 'en' ? '' : `/${locale}`}/demo/procurement/`;
}

export function projectPath(locale: Locale): string {
  return `${locale === 'en' ? '' : `/${locale}`}/projects/procurement/`;
}
