import type { en } from './en';

export const ro: typeof en = {
  meta: {
    homeTitle: 'Optimix — Optimizarea proceselor de afaceri',
    homeDescription: 'Optimix ajută echipele să transforme transferurile manuale repetate în fluxuri controlate, păstrând deciziile și excepțiile la oameni.',
    contactTitle: 'Pregătește descrierea unui proces — Optimix',
    contactDescription: 'Descrie un proces repetitiv, persoanele și sistemele implicate și locurile unde activitatea încetinește.',
    privacyTitle: 'Informații privind confidențialitatea — Optimix',
    privacyDescription: 'Stadiul formularului de contact și al informării privind confidențialitatea Optimix.',
  },
  ui: {
    skip: 'Sari la conținut', process: 'Proces', approach: 'Abordare', contact: 'Contact',
    brief: 'Descrie un proces', briefShort: 'Descrie procesul', menu: 'Meniu', language: 'Limbă',
    backTop: 'Înapoi sus', home: 'Acasă', privacy: 'Confidențialitate',
    footerLine: 'Îmbunătățirea proceselor prin fluxuri digitale controlate.',
  },
  hero: {
    eyebrow: 'Proiectarea proceselor operaționale',
    lines: ['Fiecare transfer', 'trebuie să ducă', 'lucrurile înainte.'],
    intro: 'Optimix ajută echipele în creștere să transforme transferurile manuale repetate în fluxuri controlate. Sistemele gestionează rutina; oamenii păstrează aprobările și excepțiile.',
    secondary: 'Vezi un exemplu de proces', previewLabel: 'Secvență ilustrativă de achiziții',
    preview: ['Cerere primită', 'Reguli verificate', 'Persoană aprobă', 'Decizie înregistrată'],
    credit: 'Imagine conceptuală pentru evaluarea designului. Nu este un proiect al unui client.',
    artAlt: 'Birou de achiziții ilustrativ, cu persoane care analizează documente; imagine generată, nu un proiect al unui client Optimix.',
  },
  problem: {
    eyebrow: 'Recunoaște transferul', title: 'Activitatea avansează. Contextul rămâne în urmă.',
    lead: 'O singură cerere poate trece prin mai multe instrumente și căsuțe poștale. Fiecare transfer adaugă un loc unde se așteaptă, se copiază sau se cere un status.',
    relay: [
      { title: 'Cerere prin e-mail', detail: 'Cererea ajunge în afara procesului.' },
      { title: 'Buget într-un fișier', detail: 'Aceleași date sunt introduse din nou.' },
      { title: 'Aprobare în inbox', detail: 'Statusul depinde de un răspuns.' },
      { title: 'Comandă în ERP', detail: 'Datele aprobate sunt copiate iarăși.' },
      { title: 'Status prin e-mail', detail: 'Oamenii întreabă unde a ajuns cererea.' },
    ],
    note: 'Model ilustrativ, nu descrierea activității unui client.',
    relayLabel: 'Transfer manual ilustrativ al unei cereri de achiziție',
  },
  change: {
    eyebrow: 'Ce se schimbă', title: 'Definește traseul înainte de automatizare.',
    lead: 'Scopul este un proces pe care oamenii îl pot urmări, verifica și măsura în sistemele deja folosite.',
    rows: [
      { label: '01 / Cartografiere', title: 'Vezi transferurile reale.', detail: 'Identifică datele de intrare, responsabilii, aprobările, reintroducerea datelor și așteptarea.' },
      { label: '02 / Traseu', title: 'Conectează pașii repetabili.', detail: 'Regulile și validarea pot deplasa activitatea de rutină prin instrumentele existente, unde este potrivit.' },
      { label: '03 / Control', title: 'Păstrează responsabilitatea deciziilor.', detail: 'Trimite cazurile ambigue și excepțiile la persoana potrivită și înregistrează rezultatul.' },
    ],
    before: 'Înainte / transferuri fragmentate',
    beforeSteps: ['Cerere prin e-mail', 'Copiere în tabel', 'Așteptarea aprobării', 'Reintroducere în ERP', 'Întrebare despre status'],
    after: 'După / traseu controlat',
    afterSteps: ['Intrare', 'Validare', 'Direcționare', 'Decizie umană', 'Execuție', 'Înregistrare'],
    afterNote: 'Excepțiile revin la o persoană. Traseul real depinde de organizație.',
  },
  workflow: {
    eyebrow: 'Un proces la vedere', title: 'Urmărește o cerere.',
    lead: 'O cerere de achiziție face traseul concret: intrare, validare, decizii umane, acțiuni ale sistemului și rezultat înregistrat.',
    disclosure: 'Flux ilustrativ de referință. Nu este un caz al unui client și nici o prezentare verificată a demonstrației Optimix existente. Pașii reali depind de organizație.',
    human: 'Om', system: 'Sistem', checkpoint: 'Punct de control', routePosition: 'Poziția pe traseu',
    bottomline: 'O verificare nereușită trebuie să ducă la o decizie, nu la un transfer invizibil.',
    steps: [
      { role: 'Om', note: 'Intrare', title: 'Cerere transmisă', detail: 'O persoană descrie necesitatea, responsabilul și informațiile de sprijin.' },
      { role: 'Sistem', note: 'Validare', title: 'Buget verificat', detail: 'Regulile definite verifică cererea înainte să avanseze.' },
      { role: 'Om', note: 'Aprobare', title: 'Decizia managerului', detail: 'O persoană autorizată aprobă, respinge sau cere o modificare.' },
      { role: 'Om', note: 'Decizie', title: 'Furnizor selectat', detail: 'Judecata rămâne la persoana responsabilă de achiziție.' },
      { role: 'Sistem', note: 'Rezultat', title: 'Comandă înregistrată', detail: 'Informațiile aprobate pot ajunge în ERP-ul existent.' },
      { role: 'Sistem', note: 'Așteptare', title: 'Livrare așteptată; stoc actualizat', detail: 'Traseul așteaptă informațiile despre livrare, apoi actualizează stocul.' },
      { role: 'Sistem', note: 'Validare', title: 'Factură verificată', detail: 'Documentele sunt comparate cu comanda; diferențele cer analiză.' },
      { role: 'Sistem', note: 'Finalizat', title: 'Indicatorii KPI / SLA actualizați', detail: 'Traseul finalizat lasă o urmă pentru analiză ulterioară.' },
    ],
    exceptionLabel: 'Excepție / analiză umană',
    exceptionDetail: 'Dacă bugetul sau informațiile nu trec verificarea, cererea se oprește. Un manager analizează problema, înregistrează decizia și o reintroduce în traseu sau o oprește.',
  },
  value: {
    eyebrow: 'Valoare pentru afacere', title: 'Justificarea trebuie să reziste și pe hârtie.',
    modelLabel: 'Model ilustrativ de evaluare economică', currentEffort: '01 / Efort actual',
    currentFormula: 'Volumul procesului × timpul de lucru × costul muncii',
    otherExposure: '02 / Alte costuri', otherFormula: 'Erori + întârzieri + costul extinderii',
    changeCost: '03 / Costul schimbării', changeFormula: 'Implementare + integrare + instruire + întreținere + responsabilitatea procesului',
    decision: 'Decizie', decisionQuestion: 'Valoarea măsurabilă depășește costul și riscul schimbării procesului?',
    footnote: 'Timpul eliberat înseamnă capacitate. Devine economie financiară doar dacă organizația poate reduce efectiv costuri sau poate redirecționa capacitatea. Orice estimare cere datele inițiale ale companiei.',
  },
  approach: {
    eyebrow: 'Principii de lucru', title: 'Începe cu procesul, apoi alege mecanismul.',
    lead: 'O colaborare rezonabilă ar începe cu observarea muncii, stabilirea punctelor de control și testarea valorii unei schimbări care trebuie întreținută.',
    note: 'Abordare propusă, nu o promisiune fixă de livrare.',
    stages: [
      { title: 'Înțelege', detail: 'Observă intrările, oamenii, sistemele, documentele și excepțiile.' },
      { title: 'Cartografiază', detail: 'Fă vizibile transferurile, așteptarea și reintroducerea datelor.' },
      { title: 'Decide', detail: 'Stabilește ce rămâne la oameni și unde este necesară aprobarea.' },
      { title: 'Construiește', detail: 'Conectează un traseu repetabil limitat, unde mediul permite.' },
      { title: 'Măsoară', detail: 'Compară noul traseu cu situația inițială.' },
      { title: 'Îmbunătățește', detail: 'Ajustează regulile pe baza activității și a excepțiilor înregistrate.' },
    ],
  },
  contactTeaser: {
    eyebrow: 'Primul pas', title: 'Alege un proces.',
    lead: 'Descrie activitatea repetitivă, persoanele implicate, instrumentele folosite și locurile unde se blochează. Este suficient pentru a începe evaluarea utilității economice a schimbării.',
    cta: 'Descrie un proces', status: 'Formularul este în pregătire. Cererile nu sunt acceptate încă.',
  },
  contactPage: {
    eyebrow: 'Descrierea procesului', title: 'Începe cu un singur proces.',
    lead: 'Nu este nevoie de o specificație tehnică. Descrie activitatea, persoanele implicate și locurile unde traseul încetinește.',
    status: 'Acest formular este o previzualizare. Nu au fost configurate adresa de livrare sau operatorul datelor, deci cererea nu poate fi trimisă încă.',
    details: 'Nu introduce documente confidențiale sau date personale sensibile.',
    name: 'Nume', company: 'Companie', email: 'E-mail de serviciu', process: 'Numele procesului',
    description: 'Descrie procesul', systems: 'Sistemele actuale', problem: 'Problema principală',
    frequency: 'Frecvența aproximativă', send: 'Trimite descrierea',
    disabled: 'Trimiterea va fi disponibilă după configurarea livrării și a informațiilor de confidențialitate.',
    privacyLink: 'Informații privind confidențialitatea',
  },
  privacyPage: {
    eyebrow: 'Confidențialitate', title: 'Informațiile privind confidențialitatea sunt în pregătire.',
    lead: 'Formularul de contact nu este activ și nu poate trimite date din acest prototip.',
    detail: 'Operatorul legal, datele de contact, scopurile prelucrării, destinatarii, perioada de păstrare și drepturile aplicabile vor fi publicate după confirmare. Această pagină nu este o informare finală privind confidențialitatea.',
    back: 'Înapoi la descrierea procesului',
  },
};
